### PR TITLE
[apm] revert https://github.com/elastic/package-storage/pull/3699

### PR DESCRIPTION
**Pull request by stuartnelson3**
reverts https://github.com/elastic/package-storage/pull/3699

to be merged shortly before 8.1.0 release

### CODE REVIEW

**Comment by mtojek** [comment]
Hi @stuartnelson3, in general, it isn't safe to remove packages from production as they might be already used and installed by customers. It may corrupt the end-user setup. Is there any strong reason why we have to do this?

**Comment by jsoriano** [comment]
This package has `kibana.version: ^8.1.0`, so it won't be used in previous versions. Why removing it?

**Comment by stuartnelson3** [comment]
The change hadn't been deployed yet. I personally don't see any reason to not release it to production now, as i do not foresee the package changing. This was a few days earlier than we would normally release it, though.

@simitt thoughts?

**Comment by stuartnelson3** [comment]
ah, this also just got the :+1: from @joshdover

**Review by joshdover — CHANGES_REQUESTED** [review]
Apologies, we need to deploy apm package 8.1.0 to prod, not revert it.

**Comment by stuartnelson3** [comment]
k, closing this and releasing 8.1.0 to prod.

**Pull request closed without merging**
