### PR TITLE
Remove packages as master is not production anymore

### PR DESCRIPTION
**Pull request by ruflin**
As part of #86 the master branch will not be used anymore. By now, all packages have been moved over to the production branch and it is ready to be deployed under `epr.elastic.co`. All future contributions of packages should go to the production branch or as soon as staging and snapshot deployment are fully available + promotion script, follow the new process.

This PR removes all packages and big junk of the code. Further cleanup will be needed. The goal of this PR is to make sure this registry is not used anymore moving forward.

### CODE REVIEW

**Comment by ruflin** [comment]
Only opening as draft at the moment as I'm pretty sure there will be also other side effects in the integrations and package-registry repo that first need to be sorted out. @mtojek FYI

**Comment by ruflin** [comment]
Opened for review as I think all the dependencies in package-registry should be removed now.

**Comment by mtojek** [comment]
I was wondering if this is the moment, when the entire master branch can be deleted?

**Comment by ruflin** [comment]
@mtojek My thinking was that the master/main branch will become more a landing page of this repository. Explaining the branches and who things are promoted etc. Lets get first this PR in to make sure the branch is not used for packages anymore and then follow up.

**Comment by mtojek** [comment]
I can also consider a different approach here - add explanation to README files and set "production" as default branch.

**Comment by ruflin** [comment]
I filed as a follow up so we don't forget: https://github.com/elastic/package-storage/issues/120

**Pull request merged**
