### PR TITLE
Updating kibana config

### PR DESCRIPTION
**Pull request by ycombinator**
Updates the `kibana.config.yml` file used by the Docker container, per guidance from @skh here: https://github.com/elastic/package-storage/pull/133#issuecomment-658371941

### CODE REVIEW

**Comment by ycombinator** [comment]
CI failure is unrelated and should be resolved once https://github.com/elastic/package-storage/pull/135 is merged.

**Comment by jonathan-buttner** [comment]
Does this PR need to be opened up against the `production` branch?

**Comment by ycombinator** [comment]
Thanks @jonathan-buttner, I just opened backport PRs against `production` and `staging` branches. I'd done one for `snapshot` earlier.

**Comment by jonathan-buttner** [comment]
Will see if CI passes on this one: https://github.com/elastic/package-storage/pull/140

**Comment by jonathan-buttner** [comment]
ah ok haha, I just opened one too. I'll close it. Thanks!

**Pull request merged**
