### PR TITLE
[snapshot] Update "azure_metrics" package to version 1.0.2

### PR DESCRIPTION
**Pull request by bmorelli25**
This PR updates `azure_metrics` package to version 1.0.2.

Changes: https://github.com/bmorelli25/package-storage/commit/6a603f61fd13fb99398807f9f4561b1add3ccfc8

### CODE REVIEW

**Comment by bmorelli25** [comment]
I'm trying to get the changes in https://github.com/elastic/integrations/pull/2656 to the production endpoint. I think this is the first step. I think the next step is to run `elastic-package promote` and choose `snapshot-production`. Does that sound right?

**Review by andrewkroh — CHANGES_REQUESTED** [review]
Changes from elastic/integrations are automatically sycned into the snapshot branch. For example azure_metrics 1.0.2 ([PR](https://github.com/elastic/package-storage/pull/3612)) and 1.0.3 ([PR](https://github.com/elastic/package-storage/pull/3863))are already present in the snapshot branch.

Is this modifying the package beyond what `elastic-package build` produced? It looks like you are correcting the markdown that `elastic-package build` generated. If there's a problem with the output then IMO that should be corrected in `elastic-package` so that this is automated.

**Comment by bmorelli25** [comment]
Ahh, I see. No, I'm not modifying anything outside of what was modified in https://github.com/elastic/integrations/pull/2656. I just need to get those changes (1.0.2) into production so that our doc build scrip uses the new changes.

**Comment by bmorelli25** [comment]
Replaced with https://github.com/elastic/package-storage/pull/4321 and https://github.com/elastic/package-storage/pull/4322.

**Pull request closed without merging**
