### PR TITLE
[production] Promote packages from snapshot (linux-0.6.8, nginx-1.4.1)

### PR DESCRIPTION
**Pull request by colleenmcginnis**
This PR promotes packages from `snapshot` to `production`.

Promoted packages:
* `linux-0.6.8: 6ed5680775de6ced`
* `nginx-1.4.1: fe6a75771387c22c`

### CODE REVIEW

**Comment by mtojek** [comment]
Hi Colleen!

No worries regarding production update as the stage responsible for building Docker images is `Publish Docker image`, and it passed. The stage that failed is `v2: Sync packages` and it's related to migration packages from v1 to v2. I'm working on making this step passing too.

Anyway, you should be good to rollout a new deployment and see your changes live.

**Comment by colleenmcginnis** [comment]
Thanks @mtojek! I did try to run the updates to the docs, but I'm not seeing these latest versions reflected. Should I expect to see a result here (https://epr.elastic.co/package/nginx/1.4.1/)? In the docs update process, it is still saying 1.3.1 is the latest for `ngixn` (https://epr.elastic.co/package/nginx/1.3.1/).

**Comment by mtojek** [comment]
You also need to perform step 2. of this [guide](https://github.com/elastic/integrations/blob/main/docs/developer_workflow_promote_release_integration.md). It will roll out all changes.

**Comment by colleenmcginnis** [comment]
Ahh. You must have done that step for me [last time](https://github.com/elastic/package-storage/pull/4665#issuecomment-1162737428). 🙂

**Pull request merged**
