### PR TITLE
[snapshot] First APM package ever

### PR DESCRIPTION
**Pull request by jalvz**
🎉

### CODE REVIEW

**Comment by jalvz** [comment]
@ruflin @mtojek `lint` is failing because it needs https://github.com/elastic/package-registry/pull/656, which is not yet into the last tagged version of the registry.

I'd like to merge this asap to start "serious testing ™️ ": is it ok to do it before releasing a new registry version, or something bad will happen? 
OTOH, when should we expect a new registry/spec release?

**Comment by ruflin** [comment]
I suggest we just do a new release of the registry and spec today? @mtojek @ycombinator Do you see any problem with that?

**Review by axw — APPROVED** [review]
LGTM!

**Comment by jalvz** [comment]
> I suggest we just do a new release of the registry and spec today?

@ruflin @mtojek @ycombinator who usually takes care of that, and/or where are the docs for that matter? - ie. any specific release procedure beyond tagging the latest commit?

**Review by mtojek — COMMENTED** [review]
Let's first make this PR green.

It looks like there is a problem with validation: no support for traces. I suppose that's because of not bumped up revision in the package storage repository (Dockerfile: https://github.com/elastic/package-storage/blob/snapshot/Dockerfile#L7).

Here are the steps on how to prepare and release the next revision of package-registry: https://github.com/elastic/package-registry#release

**Comment by ruflin** [comment]
@jalvz Can you prepare a new release for the registry? @mtojek Can you assist him?

**Comment by jalvz** [comment]
> It looks like there is a problem with validation: no support for traces. I suppose that's because of not bumped up revision

Exactly, that's why we need a release first (see https://github.com/elastic/package-storage/pull/688#issuecomment-739804776)

PR up: https://github.com/elastic/package-registry/pull/661

**Comment by jalvz** [comment]
This is green now, thanks all. Can some of you have a loot at 4322c2413bfca6cf648c7c340f2de89152b3f9d5 ?

**Review by mtojek — APPROVED** [review]
The CI is green, LGTM!

Keep in mind that you'll have to adjust also other branches (staging, production) with the updated registry version.

**Comment by ph** [comment]
This is great! !

**Pull request merged**
