### PR TITLE
[staging] Remove promoted packages

### PR DESCRIPTION
**Pull request by mtojek**
This PR removes packages promoted to prod.

Left:
none

### CODE REVIEW

**Comment by mtojek** [comment]
The fun fact is that 0.13.0 was promoted to prod, but 0.12.0 left here :)

**Comment by mtojek** [comment]
Nothing relevant on the CI side.

**Comment by ruflin** [comment]
It seems sometimes tests are flaky especially on the netflow package. I wonder why? 

@adriansr This is the output:

```

[2020-08-04T11:32:03.132Z]         --- FAIL: TestSetup/install-packages/netflow-0.2.1 (7.44s)

[2020-08-04T11:32:03.132Z]             main_integration_test.go:117: http: invalid Read on closed Body
```

We should probably also have a better error on the test script ...

**Comment by ruflin** [comment]
I did rerun CI just to be sure it is just flaky.

**Comment by mtojek** [comment]
I would say it's a transient network error. Most likely we'll have to adopt some retry mechanism. I wonder if it's the same in the wild, while working with real Kibana instances on daily basis.

**Pull request merged**
