### PR TITLE
Clean snapshot branch after promotion

### PR DESCRIPTION
**Pull request by mtojek**
Follow up of: https://github.com/elastic/package-storage/pull/146

I will push both PRs together in-sync.

### CODE REVIEW

**Comment by mtojek** [comment]
It failed with HTTP 500 now:

```
[2020-07-20T14:59:49.043Z]         --- FAIL: TestSetup/install-packages/netflow-0.1.1 (0.48s)
[2020-07-20T14:59:49.043Z]             main_integration_test.go:113: 
[2020-07-20T14:59:49.043Z]                 	Error Trace:	main_integration_test.go:113
[2020-07-20T14:59:49.043Z]                 	Error:      	Not equal: 
[2020-07-20T14:59:49.043Z]                 	            	expected: 200
[2020-07-20T14:59:49.043Z]                 	            	actual  : 500
[2020-07-20T14:59:49.043Z]                 	Test:       	TestSetup/install-packages/netflow-0.1.1
```

**Comment by ycombinator** [comment]
> Ehh.. I think I know what's the issue. The staging branch hasn't been pushed and I've just cleaned up all packages from snapshot and they're not available :)

:) Since snapshot reads from staging+snapshot(+production), I guess we should push the staging branch first then?

**Comment by mtojek** [comment]
I guess we have an issue to solve in the future, but temporarily we need to push them together (acknowledged risk).

**Comment by ycombinator** [comment]
> I guess we have an issue to solve in the future, but temporarily we need to push them together (acknowledged risk).

If we push the staging branch first, wouldn't the packages start appearing in the snapshot registry's search service and therefore make CI pass on this PR?

**Comment by mtojek** [comment]
I merged the other PR.

I assume that "eventually" they will be fine once docker images are rebuilt and published:

```
FROM docker.elastic.co/package-registry/distribution:production AS production
FROM docker.elastic.co/package-registry/distribution:staging AS staging

FROM docker.elastic.co/package-registry/package-registry:v0.7.0
LABEL package-registry=v0.7.0

COPY --from=production /packages/production /packages/production
COPY --from=staging /packages/production /packages/staging

# Adds specific config and packages
COPY deployment/package-registry.yml /package-registry/config.yml
COPY packages /packages/snapshot

WORKDIR /package-registry

# Sanity check on the packages. If packages are not valid, container does not even build.
RUN ./package-registry -dry-run
```

**Comment by ycombinator** [comment]
I see, so either we wait for those images to be built or we go ahead and merge this PR now, assuming some risk. Is that what you're suggesting?

**Comment by mtojek** [comment]
Yes, precisely. This time I would be for the second option.

**Comment by ycombinator** [comment]
Gotcha, I'm on the same page as you now. And I assume there's some urgency due to which we must merge this PR now? We can't wait for the "proper" process to happen, where the images are rebuilt and the snapshot registry returns staging packages?

**Comment by mtojek** [comment]
> Gotcha, I'm on the same page as you now. And I assume there's some urgency due to which we must merge this PR now?
I'm not sure when can we expect the docker images to be published. It would be good to have the staging updated to ease testing packages.

**Comment by ycombinator** [comment]
> I'm not sure when can we expect the docker images to be published. It would be good to have the staging updated to ease testing packages.

Since https://github.com/elastic/package-storage/pull/146 is merged now, doesn't that take care of staging being updated? Sorry, it's possible I'm just missing something about how the registry works.

**Comment by mtojek** [comment]
> Since #146 is merged now, doesn't that take care of staging being updated?

I didn't see any docker image got published yet.

**Comment by ycombinator** [comment]
I guess the part I'm not following is how will merging this PR here ease testing packages?

**Comment by mtojek** [comment]
There is a plan to use the oblt clusters agains release candidates and staging. Developers wouldn't have to boot up local clusters.

**Comment by mtojek** [comment]
Alright, so the issue is fixed. There is a transient one now: 

```
[2020-07-20T17:13:56.487Z]         --- FAIL: TestSetup/install-packages/netflow-0.2.0 (6.96s)
[2020-07-20T17:13:56.487Z]             main_integration_test.go:117: http: invalid Read on closed Body
```

I think we can ignore this one. Merging.

**Pull request merged**
