### PR TITLE
Remove _* folders from existing packages

### PR DESCRIPTION
**Pull request by ycombinator**
This PR removes `_*` folders from existing packages. Such folders are only intended for development and show not be present in packages being served by the package registry, i.e. packages in the `package-storage` repository.

Note: since these folders are only expected at development time anyway, there is no need to re-deploy the `production` package registry after this PR is merged.

In preparation for https://github.com/elastic/package-storage/pull/1096.
Related: https://github.com/elastic/package-storage/issues/925

### CODE REVIEW

**Comment by ycombinator** [comment]
I tagged multiple reviewers from the APM Server team but I think any one of their approvals should suffice.

**Review by mtojek — APPROVED** [review]
LGTM

**Review by axw — APPROVED** [review]

**Comment by ruflin** [comment]
Could we have the validator to check that no directories exist which should not be there?

**Comment by ycombinator** [comment]
> Could we have the validator to check that no directories exist which should not be there?

I assume you are referring to validation using the package spec. If so, ideally yes, this is how we could do this validation! 

However, the challenge is that the package spec, at least in its current form, reflects the structure of a "source" package. In source packages, folders such as `_dev` are expected to be there, as are `README` template files, un-encoded dashboard asset files, etc. When `elastic-package build` is run on a source package, a "built" package is produced and some of these folders/files are no longer present; this is by design as these folders/files are typically only required for package development, not as part of the package that needs to be served from the package registry.

What we need is either a parallel package spec for "built" packages or some way of annotating the current package spec with expectations for "built" packages. Once we have that, we should let the package spec validate "built" packages as well and use that feature in this repo. Until then, this PR (and it's [associated cousins](https://github.com/elastic/package-storage/issues/925#issuecomment-814039667)) provide a bit of a stop-gap.

**Comment by ruflin** [comment]
I definitively prefer to have only 1 package spec but follow the annotate approach or similar you mentioned.

**Pull request merged**
