### PR TITLE
Endpoint package version 0.2.0

### PR DESCRIPTION
**Pull request by jonathan-buttner**
Releasing new endpoint package

### CODE REVIEW

**Comment by jonathan-buttner** [comment]
@ruflin will we need to merge this to the `experimental` branch as well?

**Comment by kevinlog** [comment]
@jonathan-buttner had a quick chat with @nnamdifrankie 

We just wanna make sure that we're prepared to merge a PR on our end as these package changes are currently causing some local test failures

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner had a quick chat with @nnamdifrankie
> 
> We just wanna make sure that we're prepared to merge a PR on our end as these package changes are currently causing some local test failures

Thanks for the note Kevin. @nnamdifrankie I'll be on PTO today. One thought I had to avoid this PR causing test failures is to temporarily change the metadata index pattern here like we did for policy: https://github.com/elastic/kibana/blob/master/x-pack/plugins/siem/server/endpoint/alerts/index_pattern.ts#L80

We can change it to `metrics-endpoint.metadata-default` and update the tests. That way when this PR gets merged it won't cause failures. Then once the registry starts serving the new package and we can put in another PR to remove the hardcoded value.

Otherwise I don't think we're going to be able to completely avoid some test failures. Once this PR is merged there is some lag time with the CDN so if we merge the PR to update the tests too soon we'll get failure there too.

**Comment by kevinlog** [comment]
> Thanks for the note Kevin. @nnamdifrankie I'll be on PTO today. One thought I had to avoid this PR causing test failures is to temporarily change the metadata index pattern here like we did for policy: https://github.com/elastic/kibana/blob/master/x-pack/plugins/siem/server/endpoint/alerts/index_pattern.ts#L80

> We can change it to metrics-endpoint.metadata-default and update the tests. That way when this PR gets merged it won't cause failures. Then once the registry starts serving the new package and we can put in another PR to remove the hardcoded value.

> Otherwise I don't think we're going to be able to completely avoid some test failures. Once this PR is merged there is some lag time with the CDN so if we merge the PR to update the tests too soon we'll get failure there too.

@nnamdifrankie would it work if we push a PR to disable the tests that could fail.  We could also have the changes required for this in place in the disabled tests, then enable them after this is in. I know it sounds like a lot of back and forth, but my goal is to not block people across the org.  What are your thoughts?

In the meantime, we should figure out how to handle these types of cases moving forward - it's going to become more common I suspect.

**Comment by nnamdifrankie** [comment]
@kevinlog  we can disable them before the package is released and then submit our change after to enable them. I am fixing them now, it is not a lot of changes only for metadata.

**Comment by ruflin** [comment]
@jonathan-buttner I assume we don't need any changes in experimental for 7.8 as no code changes are pushed anymore to 7.8 on the endpoint side.

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner I assume we don't need any changes in experimental for 7.8 as no code changes are pushed anymore to 7.8 on the endpoint side.

Ah good point. Yep that's correct. Thanks!

**Pull request merged**
