### PR TITLE
Update staging Dockerfile to use new registry

### PR DESCRIPTION
**Pull request by ruflin**
This also cleans up the Dockerfile by using two stages. It includes the production packages from the production distribution instead of git.

### CODE REVIEW

**Comment by mtojek** [comment]
What do you think about the following idea:
if you perform the cleanup, you can use the docker image for empty package-registry and extend it with package-storage distro.

I think you can consider to build Docker images from github repo (package-registry):

```
$ docker build https://github.com/docker/rootfs.git#container:docker
```

(I'm fine with potential follow-ups).

**Comment by ruflin** [comment]
@mtojek Not sure I fully follow. What does extend in this case mean? How would the Dockerfile of staging look like or will this become obsolete?

**Comment by mtojek** [comment]
We can assume that all environments (snapshot, staging, production) have same image definitions. I think it would be beneficial to have a single common Docker image definition and the last layer defines added packages.

If I want to update the package-registry commit reference, I have to push to 3 different branches, which looks like a code smell. It would be good to have a single place for that.

**Comment by ruflin** [comment]
I would prefer to keep the registry version independent. It means we can start testing a more recent version of the registry on snapshot and only then roll it out to staging and production.

**Comment by ruflin** [comment]
BTW: This does not mean we cannot find a single place for it in a separate branch or similar. Because agree, the multiple PR's are cumbersome, at the same time it is nice that CI is run on these changes directly.

**Comment by ruflin** [comment]
@mtojek So this discussion is not lost, should we open a new issue?

**Comment by mtojek** [comment]
It would valuable, for sure. I see a value in covering also the integrations repository. It seems that we may face the same issue there,  and I can bet it's also the same for Endpoint.

**Comment by ruflin** [comment]
@mtojek Could you follow up with an issue? Perhaps in the integrations repo?

**Pull request merged**
