### PR TITLE
Delete Dockerfile

### PR DESCRIPTION
**Pull request by mtojek**
This Dockerfile allows to build the `package-registry` with a specific revision of the `package-storage`. The Dockerfile in the `package-registry` allows for the same (`mage build`).

### CODE REVIEW

**Comment by ruflin** [comment]
Hm, wait. I think we can't just remove this as it will break CI. Please hold off.

**Comment by mtojek** [comment]
Good catch, @ruflin 

At the moment, we have two different projects that push images to Docker repository:
1. `package-registry` pushes to `docker.elastic.co/package-registry/package-registry`
2. `package-storage` pushes to `docker.elastic.co/observability-ci/package-registry`

I believe this a good moment to clean it up and pick a one project that pushes new docker images. Otherwise we will always have race conditions.

**Comment by kuisathaverat** [comment]
Those two namespaces are for different purposes `docker.elastic.co/observability-ci` is for CI images and it will have commit oriented Docker images and not necessary to be public available. And `docker.elastic.co/package-registry` used for public and stable Docker images. The reason to use two namespaces it is because you do not need the amount of images we will need in the CI to be public, them will be noise for most of the people but are not for the CI.

**Comment by mtojek** [comment]
@kuisathaverat I understand the concerns about release noise, but that wasn't my point here.

I'm not convinced if we need pushes to the "observability-ci" namespace:
1. If there is a new commit in master branch for the package-registry, it will not trigger rebuilding and pushing an image with the "package-storage".
2. If there is a new commit in master branch for the "package-storage", it will not trigger rebuilding and pushing an image with the "package-storage".

I assume the best option for us would be rebuilding the docker image for package registry if any of projects (package-registry, package-storage) changes. Otherwise, it's hard to track/predict which changes have been pulled in.

**Comment by kuisathaverat** [comment]
>I assume the best option for us would be rebuilding the docker image for package registry if any of projects (package-registry, package-storage) changes. Otherwise, it's hard to track/predict which changes have been pulled in.

ok, I got you, you are right we are pushing from two different projects the same image, it could be a little random. What about to push only from package-registry repo in the following way?

* When a merge to the package registry we push as we do now.
* When a merge to package storage we launch a build on the same branch name for the package registry and push as we do now.

In this way, only the package registry builds push Docker images but it does it on changes on the package registry repo or in the docker registry repo.

**Comment by mtojek** [comment]
Yes, I was thinking exactly about the same flow. Well, I'm still a bit afraid of a race condition if two projects got Git-pushed at the same time, but it's definitely a better solution.

WDYT @ruflin? Should we go for it?

**Comment by ruflin** [comment]
The reason why we have to projects pushing is exactly as you described. If we can trigger a build of the other from one, ++ on doing. As the package-storage will change much more often, I would argue it should probably be pushed from the package-storage instead. This also has an interesting side effect, that we can also enabled it for branches like we have the `experimental` one at the moment. At the same time, I don't expect that to happen often in the future.

One other thought related to this here is: Should we have a Docker image available for the registry with no packages so the packages can be mounted in?

**Comment by mtojek** [comment]
> One other thought related to this here is: Should we have a Docker image available for the registry with no packages so the packages can be mounted in?

Hmm, I'm not convinced about this case. It requires a mounted volume, so we can always mount the default image with packages and simply clean then.

It would make sense to publish the registry without packages if we decide to use Docker images differently - layer by layer. First layer - the registry, second one - packages. Then we can swap the storage layer with anything we want. This is fine, but it needs redesigning Dockerfiles a bit.

**Comment by ruflin** [comment]
I realised on my end, what you proposed initially to have in the package-registry is the right place. Two reasons:

* If someone wants to run it and have a look at the Dockerfile, he will go to the package-registry
* The package-storage is a Github repo but could also be S3 and it would be strange to have the Dockerfile there.

++ on what you initially proposed.

**Comment by mtojek** [comment]
> I realised on my end, what you proposed initially to have in the package-registry is the right place.

I will clean also some parts of the `.ci` directory.

**Pull request merged**
