### PR TITLE
Promote packages from snapshot to staging

### PR DESCRIPTION
**Pull request by mtojek**
This PR copies all packages, except "snapshot" from "snapshot" branch to "staging" one.

### CODE REVIEW

**Comment by ycombinator** [comment]
I imagine there will be an analogous PR to remove these packages from `snapshot`?

**Comment by mtojek** [comment]
Yes @ycombinator , that's the plan. I wanted to have this PR green/healthy first and then wrap up a new one for snapshot.

**Comment by ycombinator** [comment]
I checked out this PR and diff'd it against the `snapshot` branch. Most of the changes are as expected. The one change I think needs to be in the `staging` branch (either via this PR or a separate one) is:

```
diff --git a/testing/main_integration_test.go b/testing/main_integration_test.go
index 4f539f0..c97b614 100644
--- a/testing/main_integration_test.go
+++ b/testing/main_integration_test.go
@@ -128,7 +128,7 @@ type Package struct {
 }

 func getPackages(t *testing.T) ([]string, error) {
-       resp, err := http.Get("http://localhost:8080/search?experimental=true")
+       resp, err := http.Get("http://localhost:8080/search")
```

That is, we need `?experimental=true` in the `staging` branch as well, now that most packages are marked `experimental`. Otherwise the integration tests will fail. Integration tests are failing on CI but I'm not certain this is the cause. Nevertheless I think we should fix it.

**Comment by mtojek** [comment]
You're absolutely right. I forgot about this flag at all, thanks!

**Comment by mtojek** [comment]
Confirmed with Kibana team, that the issue with HTTP 409 is known and the fix might not be picked up by the CI yet.

Only need to solve this one: https://github.com/elastic/package-storage/pull/148

**Pull request merged**
