### PR TITLE
[apm] update apm production package with correct var types

### PR DESCRIPTION
**Pull request by jalvz**
Update APM production package with correct var types

Closes https://github.com/elastic/package-storage/issues/1011

### CODE REVIEW

**Review by mtojek — CHANGES_REQUESTED** [review]
Please fill up the issue description justifying the PR.

Please link the appropriate Github issue.

**Review by mtojek — APPROVED** [review]

**Comment by mtojek** [comment]
I understand that this is an acknowledged risk to push directly to production branch, right?

**Comment by jalvz** [comment]
Today I tried elastic-package following https://github.com/elastic/elastic-package#getting-started and that didn't work.

After running `make build` there is no `integrations` folder (can't `cd integrations`). I didn't have time to dig deeper, so I guess so. I will get back to it next week, didn't want to prevent my colleagues from testing with a prod package in the meanwhile.

**Comment by ycombinator** [comment]
Hey @jalvz, ++ for getting this PR in so your colleagues are unblocked. And thank you for trying out `elastic-package`. I see that the README has a step to `cd integrations` which obviously isn't generally applicable. I will fix the README now so it's clearer.

**Comment by ruflin** [comment]
To make a package available for testing, it is not required to be in the production branch, see table here: https://github.com/elastic/package-storage#package-storage

As soon as APM because a package that is installed by default pushing to production directly is very risky as it might affect all of Kibana. We should only do this as an exception.

**Comment by ycombinator** [comment]
> I will fix the README now so it's clearer.

https://github.com/elastic/elastic-package/pull/285

**Pull request merged**
