### PR TITLE
Backport azure package

### PR DESCRIPTION
**Pull request by exekias**
This PR backports the `azure` integration to 7.9.

I have adapted the breaking changes around renaming `config_templates` and `dataset`

image

image

I manually tested the package installs correctly

### CODE REVIEW

**Comment by exekias** [comment]
@ruflin @mtojek do you think it would be possible to get this in the 7.9 package registry?

**Comment by mtojek** [comment]
There was an image pushed under: `docker.elastic.co/observability-ci/package-registry/distribution:PR-606`

I think you can check if it works as intended.

**Review by mtojek — APPROVED** [review]
LGTM

**Comment by exekias** [comment]
Thank you, that made testing super easy

**Pull request merged**
