### PR TITLE
Update to v0.7.0 in snapshot

### PR DESCRIPTION
**Pull request by ph**

### CODE REVIEW

**Comment by ph** [comment]
thanks got another one for snapshot https://github.com/elastic/package-storage/pull/132

**Comment by ycombinator** [comment]
@ph Is the CI build failure relevant? 

```
Step 3/14 : FROM docker.elastic.co/package-registry/package-registry:v0.7.0

[2020-07-09T13:58:22.312Z] manifest for docker.elastic.co/package-registry/package-registry:v0.7.0 not found: manifest unknown: manifest unknown
```

**Comment by kuisathaverat** [comment]
the build for that tag failed https://beats-ci.elastic.co/job/Beats/job/package-registry/view/tags/job/v0.7.0/, I am checking why

**Comment by kuisathaverat** [comment]
it looks a fair error
```
[2020-07-09T13:42:10.787Z] vendor/modules.txt: needs update
[2020-07-09T13:42:10.787Z] Error: running "git update-index --refresh" failed with exit code 1
script returned exit code 1
```

**Comment by ph** [comment]
Looking at the CI build seems to have a few items there?

**Comment by ph** [comment]
@kuisathaverat I did the following I've merge the PR in master was green and created a tag, is there more to know?

**Pull request merged**
