### PR TITLE
Clean up master branch

### PR DESCRIPTION
**Pull request by ruflin**
All the packages and testing was moved of the master branch. The master branch mainly contains docs and some share scripts for the different branches, but most files were not needed anymore.

The following has been removed:

* Test environment: This is contained in each branch an moving forward `elastic-package stack up` should be used for this
* Magefiles: The commands in the magefile were not needed anymore as no test code exists anymore
* go.* mod files: Not needed anymore as also mage was removed

### CODE REVIEW

**Comment by ruflin** [comment]
@kuisathaverat Can I remove the `mage check` from CI in this branch to get it to green or will this have an effect on other branches?

**Comment by mtojek** [comment]
@ruflin it looks like it's just "Lint". Let's try to clean it.

**Comment by ruflin** [comment]
@mtojek I now removed most of CI, it mainly stays around in case we need it again. What I'm worried is that maybe (don't ask me how) an other branch uses parts of this? @kuisathaverat can hopefully confirm if it is save to get this in or not.

**Review by kuisathaverat — APPROVED** [review]
LGTM

**Pull request merged**
