### PR TITLE
Mergify configuration

### PR DESCRIPTION
**Pull request by cachedout**
This is a Mergify configuration as discussed [here](https://github.com/elastic/package-storage/issues/592#issuecomment-781391630).

As [discussed here](https://github.com/elastic/package-storage/issues/592#issuecomment-781960822), I've just included the first half of the originally proposed configuration.

This will not be functional until a corresponding PR is merged relating to an issue filed in a private repo. Since that issue is private and this repo is public, please refer to the [public issue in this repo for the reference to it](https://github.com/elastic/package-storage/issues/592).

### CODE REVIEW

**Review by v1v — APPROVED** [review]
I don't know what's the merge policy but `method: squash` might be something interesting if there are multiple commits?

**Comment by cachedout** [comment]
> I don't know what's the merge policy but method: squash might be something interesting if there are multiple commits?

Seems fine to me but I'll defer to @mtojek for his preference.

**Review by kuisathaverat — APPROVED** [review]

**Review by mtojek — APPROVED** [review]
I don't have any preferences here, but agree with @v1v that multiple commits can be squashed.

**Comment by cachedout** [comment]
Cool. I just went ahead and changed the merge method to `squash. Since it has the required reviews, I'll merge it assuming that tests pass.

**Comment by mtojek** [comment]
@cachedout I think you are good to go now.

**Pull request merged**
