### PR TITLE
[production] Promote packages from snapshot to production

### PR DESCRIPTION
**Pull request by mtojek**
This PR promotes packages from `snapshot` to `production`.

Promoted packages:
* `system-0.8.0: 47fa3e45bad0a4ad`

### CODE REVIEW

**Comment by mtojek** [comment]
Unfortunately flaky tests appear:

```
[2020-10-16T07:28:02.258Z] --- FAIL: TestSetup (317.79s)
[2020-10-16T07:28:02.258Z]     main_integration_test.go:82: 
[2020-10-16T07:28:02.258Z]         	Error Trace:	main_integration_test.go:82
[2020-10-16T07:28:02.258Z]         	Error:      	Not equal: 
[2020-10-16T07:28:02.258Z]         	            	expected: 200
[2020-10-16T07:28:02.258Z]         	            	actual  : 503
[2020-10-16T07:28:02.258Z]         	Test:       	TestSetup
[2020-10-16T07:28:02.258Z]     --- FAIL: TestSetup/install-packages (202.89s)
[2020-10-16T07:28:02.258Z]         --- FAIL: TestSetup/install-packages/apache-0.1.4 (0.36s)
[2020-10-16T07:28:02.258Z]             main_integration_test.go:119: 
[2020-10-16T07:28:02.258Z]                 	Error Trace:	main_integration_test.go:119
[2020-10-16T07:28:02.258Z]                 	            				main_integration_test.go:101
[2020-10-16T07:28:02.258Z]                 	Error:      	Not equal: 
[2020-10-16T07:28:02.259Z]                 	            	expected: 200
[2020-10-16T07:28:02.259Z]                 	            	actual  : 500
[2020-10-16T07:28:02.259Z]                 	Test:       	TestSetup/install-packages/apache-0.1.4
[2020-10-16T07:28:02.259Z]         --- FAIL: TestSetup/install-packages/aws-0.2.4 (0.24s)
[2020-10-16T07:28:02.259Z]             main_integration_test.go:119: 
[2020-10-16T07:28:02.259Z]                 	Error Trace:	main_integration_test.go:119
[2020-10-16T07:28:02.259Z]                 	            				main_integration_test.go:101
[2020-10-16T07:28:02.259Z]                 	Error:      	Not equal: 
[2020-10-16T07:28:02.259Z]                 	            	expected: 200
[2020-10-16T07:28:02.259Z]                 	            	actual  : 500
[2020-10-16T07:28:02.259Z]                 	Test:       	TestSetup/install-packages/aws-0.2.4
[2020-10-16T07:28:02.259Z]         --- FAIL: TestSetup/install-packages/barracuda-0.1.0 (0.18s)
[2020-10-16T07:28:02.259Z]             main_integration_test.go:119: 
[2020-10-16T07:28:02.259Z]                 	Error Trace:	main_integration_test.go:119
[2020-10-16T07:28:02.259Z]                 	            				main_integration_test.go:101
[2020-10-16T07:28:02.259Z]                 	Error:      	Not equal: 
[2020-10-16T07:28:02.259Z]                 	            	expected: 200
[2020-10-16T07:28:02.259Z]                 	            	actual  : 500
[2020-10-16T07:28:02.259Z]                 	Test:       	TestSetup/install-packages/barracuda-0.1.0
```

https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackage-storage/detail/PR-481/1/pipeline/166

**Comment by mtojek** [comment]
jenkins run the tests please

**Comment by mtojek** [comment]
LGTM

**Comment by ruflin** [comment]
We should investigate the flaky tests so we can get rid fo them in the future. It would be nice to be able to access KB and ES logs for debugging these.

**Pull request merged**
