### PR TITLE
Add promote script

### PR DESCRIPTION
**Pull request by ruflin**
Initial draft of the promote script to promote a package from one branch to an other.

This script does not necessarly belong here but didn't find a better place. Only opening as draft for now.

### CODE REVIEW

**Comment by ruflin** [comment]
@mtojek I started to work on the "promote" script. It is not complete yet and I want to get the magic from your script in about using a Github API key.

**Comment by mtojek** [comment]
I understand that this PR will deprecate the existing tooling (update-package-storage)?

**Comment by ruflin** [comment]
@mtojek No, this script should only promote packages from one release to the next. We will still need the update-package-storage script but need to adjust it.

**Comment by ruflin** [comment]
Closing this PR as probably not needed in this form.

**Pull request closed without merging**
