### PR TITLE
Add new packages from rsa2elk for 7.10.0

### PR DESCRIPTION
**Pull request by adriansr**
This adds or updates the following modules:

- sophos (0.1.0)
- barracuda (0.2.0)
- f5 (0.2.0)
- citrix (0.2.0)
- cyberark (0.1.0)
- juniper (0.2.0)
- proofpoint (0.2.0)
- symantec (0.1.0)

image

### CODE REVIEW

**Comment by ruflin** [comment]
@jonathan-buttner @nnamdifrankie It seems the endoint package with transform currently breaks the CI. Could you check on how to make the package work again or adjust it the way needed?

**Comment by jonathan-buttner** [comment]
> @jonathan-buttner @nnamdifrankie It seems the endoint package with transform currently breaks the CI. Could you check on how to make the package work again or adjust it the way needed?

Hopefully this one will fix it: https://github.com/elastic/package-storage/pull/401

**Review by mtojek — APPROVED** [review]
LGTM

I assume that these packages don't have to exist in integrations.

**Review by LUGO022 — COMMENTED** [review]
Thank you

**Pull request merged**
