### PR TITLE
Add endpoint package to experimental branch

### PR DESCRIPTION
**Pull request by ruflin**
Turns out the 7.8 branch of Kibana does not work if the endpoint package is not around. I think this is unexpected but this should fix it for now.

### CODE REVIEW

**Comment by ruflin** [comment]
@paul-tavares Would like to hear your thoughts on this. I was thinking if I do not enable the endpoint flag in 7.8, I expected the endpoint package not to be required but it seems it is.

**Comment by ruflin** [comment]
Already merged to fix a current issue but lets continue the conversation.

**Comment by jonathan-buttner** [comment]
> @paul-tavares Would like to hear your thoughts on this. I was thinking if I do not enable the endpoint flag in 7.8, I expected the endpoint package not to be required but it seems it is.

Yeah that's probably my fault. I added `endpoint` to the default list of packages that needed to be installed.

https://github.com/elastic/kibana/blob/master/x-pack/plugins/ingest_manager/common/types/models/epm.ts#L261

I guess one solution would be to have the endpoint app request that the endpoint package be installed when the endpoint app is launched (this would only happen if it is enabled). That'd be a kibana change though so I'm not sure how that works since code freeze already happened right @ruflin ?

@paul-tavares if we did that we'd probably want to add better error handling in the UI like you suggested back when the endpoint app was calling the ingest manager's `setup` routine.

**Comment by paul-tavares** [comment]
Just replied via email, but also posting here:

> If we remove the package that means that Endpoint is not runnable in 7.8 - right? (ex. indexes are not created). Is that ok?  if so, then +Nicolas Ruflin go for it :) 
>
> Re-enabling Endpoint at a later time would not be an easy thing for someone (customer?) to do either? They would need to a) first send through a change to the package to make it visible, then b) enable endpoint in kibana and finally c) run the setup that ensures Endpoint is installed. (I guess for `a)` they could also host a package registry themselves?)
>
> Do I have this right?
>
> If at all possible, I would opt for documentation rather than additional changes to Endpoint UI at the 7.8 level to handle the setup.

**Comment by paul-tavares** [comment]
@ruflin does this change impact the packages served by the package registry that the Kibana CI jobs reach out to?

**Comment by paul-tavares** [comment]
actually - Just noticed this went into `experimental` branch, so maybe there is no impact to Kibana CI :)

**Comment by ruflin** [comment]
I think the simplest path forward is to just use some docs in the 7.8 release that the Endpoint package is there but cannot be used. So no need to change code on our end.

**Pull request merged**
